"""Session state and memory (SPEC §9.1.1).

Memory is written in every phase; which parts may be read or said aloud is decided by phase scopes (§9.1.3).
These models are mutable containers, but every pure function that updates them works on a deep copy.
"""

import hashlib
from datetime import date, datetime
from enum import StrEnum

from pydantic import BaseModel, Field

from sop_agent.domain.dates import DateHint
from sop_agent.domain.enums import (
    AuthorizationStatus,
    CallerRole,
    ClaimStatus,
    ConsentStatus,
    EmotionLabel,
    EscalationReason,
    IdentityField,
    IdentityStatus,
    Path,
    Phase,
    VerifiedAs,
    VerifyStage,
)
from sop_agent.nlu.schema import ValueSource
from sop_agent.sop.directive import ActionKind, Event, PendingQuestion


class FollowUpOwner(StrEnum):
    CALLER = "caller"
    INSURER = "insurer"
    PROVIDER = "provider"


class FieldValue(BaseModel):
    """A normalized identity value and the turn it was last given."""

    value: str
    turn: int
    source: ValueSource


class IdentityState(BaseModel):
    """Identity checklist. `party_id` is written only after identity passes (V1)."""

    values: dict[IdentityField, FieldValue] = Field(default_factory=dict)
    declined: set[IdentityField] = Field(default_factory=set)
    policy_number: str | None = None
    id_kind_stated: str | None = None
    status: IdentityStatus = IdentityStatus.UNVERIFIED
    verified_as: VerifiedAs | None = None
    party_id: str | None = None
    failed_attempts: int = 0
    last_evaluated_signature: str | None = None

    def valid_values(self) -> dict[IdentityField, str]:
        """Latest valid value per field; policy_number is deliberately excluded (V5)."""
        return {name: fv.value for name, fv in self.values.items()}

    def signature(self) -> str:
        """Hash of sorted field=value pairs plus the policy number; detects new information (V2)."""
        pairs = sorted(f"{name.value}={value}" for name, value in self.valid_values().items())
        pairs.append(f"policy_number={self.policy_number or ''}")
        return hashlib.sha256("\n".join(pairs).encode("utf-8")).hexdigest()


class RepresentativeState(BaseModel):
    """Third-party caller details and consent progress (§8.1.7)."""

    caller_role: CallerRole = CallerRole.UNKNOWN
    representative_name: str | None = None
    relationship: str | None = None
    authorization: AuthorizationStatus = AuthorizationStatus.NOT_NEEDED
    consent_scenario: str = "default"
    consent_request_id: str | None = None
    consent_status: ConsentStatus = ConsentStatus.NOT_REQUESTED


class CaseHints(BaseModel):
    """What the caller said about the claim, kept from any phase for later use (cross-phase memory)."""

    case_id: str | None = None
    case_type: str | None = None
    status: ClaimStatus | None = None
    date_hint: DateHint | None = None
    keywords: list[str] = Field(default_factory=list)
    raw_mentions: list[str] = Field(default_factory=list)


class FollowUp(BaseModel):
    """A follow-up item generated by code from the data (§8.3.4)."""

    item: str
    due_date: date | None = None
    owner: FollowUpOwner


class ActionRecord(BaseModel):
    """An executed side effect and its outcome."""

    kind: ActionKind
    turn: int
    ok: bool
    detail: str = ""


class CaseLog(BaseModel):
    """What happened in this session; the source of the summary email."""

    discussed_case_ids: list[str] = Field(default_factory=list)
    questions_answered: list[str] = Field(default_factory=list)
    follow_ups: list[FollowUp] = Field(default_factory=list)
    alternatives_shared_for: set[str] = Field(default_factory=set)
    actions: list[ActionRecord] = Field(default_factory=list)


class IntentCandidate(BaseModel):
    path: Path
    confidence: float
    last_turn: int


class DeferredQuestion(BaseModel):
    """A question asked before it could be answered (§8.2.7); the text is the caller's own paraphrase."""

    text: str
    turn: int
    path: Path | None = None
    answered: bool = False


class EmotionReading(BaseModel):
    label: EmotionLabel
    intensity: int
    turn: int


EMOTION_HISTORY_LIMIT = 10


class Memory(BaseModel):
    identity: IdentityState = Field(default_factory=IdentityState)
    representative: RepresentativeState = Field(default_factory=RepresentativeState)
    case_hints: CaseHints = Field(default_factory=CaseHints)
    intent_candidates: dict[Path, IntentCandidate] = Field(default_factory=dict)
    deferred_questions: list[DeferredQuestion] = Field(default_factory=list)
    selected_case_id: str | None = None
    selected_path: Path | None = None
    excluded_case_ids: set[str] = Field(default_factory=set)
    unavailable_documents: set[str] = Field(default_factory=set)
    summary_email_override: str | None = None
    emotion_history: list[EmotionReading] = Field(default_factory=list)
    case_log: CaseLog = Field(default_factory=CaseLog)


class Counters(BaseModel):
    turn_index: int = 0
    turns_in_phase: int = 0
    off_topic_streak: int = 0
    off_topic_total: int = 0
    persuasion_attempts: int = 0
    negative_emotion_streak: int = 0
    abusive_count: int = 0
    ambiguous_reply_count: int = 0


class ChatRole(StrEnum):
    CALLER = "caller"
    AGENT = "agent"


class ChatTurn(BaseModel):
    role: ChatRole
    text: str
    turn: int


class HandoffTicket(BaseModel):
    """Live-agent handoff record (§8.5); `party_id` only when verification completed."""

    ticket_id: str
    reason: EscalationReason
    phase_at_escalation: Phase
    verified_as: VerifiedAs | None = None
    party_id: str | None = None
    caller_stated_hints: list[str] = Field(default_factory=list)
    deferred_questions: list[str] = Field(default_factory=list)
    conversation_summary: str = ""
    emotion_trend: list[EmotionLabel] = Field(default_factory=list)
    created_at: datetime


class EmailDraft(BaseModel):
    """Summary email draft; the generator arrives in M5."""

    to: str
    subject: str
    text: str
    html: str = ""


class SessionSettings(BaseModel):
    """Per-session settings fixed at creation, so rules never read the clock themselves."""

    consent_scenario: str = "default"
    today: date


class SessionState(BaseModel):
    session_id: str
    phase: Phase = Phase.VERIFY_ID
    verify_stage: VerifyStage = VerifyStage.IDENTITY
    memory: Memory = Field(default_factory=Memory)
    counters: Counters = Field(default_factory=Counters)
    pending_question: PendingQuestion | None = None
    history: list[ChatTurn] = Field(default_factory=list)
    events: list[Event] = Field(default_factory=list)
    handoff: HandoffTicket | None = None
    email_draft: EmailDraft | None = None
    session_settings: SessionSettings
    created_at: datetime
